
                             ######################
        #####################  MySQL Configuration  #####################
                             ######################

1. MySQL Configuration (Using EBS):
  - Secret for MySQL Password

###################################
File: mysql-secret.yaml
###################################

apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: bXlyb290cGFzc3dvcmQ=



2. Storage Class for Mysql:

###################################
File: mysql-sc.yaml
###################################

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer


3. Persistent Volume Claim for MySQL:

###################################
File: mysql-pvc.yaml
###################################

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-sc
  resources:
    requests:
      storage: 5Gi

4. ConfigMap for MySQL Configuration:

###################################
File: mysql-configmap.yaml
###################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    sql_mode=STRICT_TRANS_TABLES
    max_connections=100


5. Deployment for MySQL:

###################################
File: mysql-deployment.yaml
###################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-app
spec:
  selector:
    matchLabels:
      app: mysql
      tier: backend
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-config-volume
          mountPath: /etc/mysql/my.cnf
          subPath: my.cnf
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-config-volume
        configMap:
          name: mysql-config
          items:
            - key: my.cnf
              path: my.cnf


6. Service for MySQL:

###################################
File: mysql-svc.yaml
###################################

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
    tier: backend
  ports:
    - port: 3306
      targetPort: 3306
