                              ##########################
        #####################  phpMyAdmin Configuration  #####################
                              ##########################

2. phpMyAdmin Configuration:
 - Secret for phpMyAdmin Password

###################################
File: phpmyadmin-secret.yaml
###################################

apiVersion: v1
kind: Secret
metadata:
  name: phpmyadmin-secret
type: Opaque
data:
  PMA_PASSWORD: bXlyb290cGFzc3dvcmQ=


3. ConfigMap for phpmyadmin:

###################################
File: phpmyadmin-configmap.yaml
###################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config
data:
  PMA_HOST: mysql-svc
  PMA_PORT: "3306"
  
  
4. Deployment for phpMyAdmin:

###################################
File: phpmyadmin-deployment.yaml
###################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: phpmyadmin-config
              key: PMA_HOST
        - name: PMA_PORT
          valueFrom:
            configMapKeyRef:
              name: phpmyadmin-config
              key: PMA_PORT
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: phpmyadmin-secret
              key: PMA_PASSWORD


4.  Service for phpmyadmin:

###################################
File: phpmyadmin-svc.yaml
##################################

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008

